# Generated by Django 5.1.3 on 2024-11-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0002_alter_voter_voter_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="apt_number",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
